apiVersion: v1
kind: Service
metadata:
  name: ftps
  annotations:
    metallb.universe.tf/allow-shared-ip: minikube
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.99.222
  selector:
    app: ftps
  ports:
  - name: ftp-connection
    port: 21
  - name: ftp-data
    port: 20021
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftps
spec:
  selector:
    matchLabels:
      app: ftps
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: ftps
    spec:
      containers:
      - name: ftps
        image: ftps:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 21
        - containerPort: 20021
        volumeMounts:
        - name: ftps-storage
          mountPath: /var/lib/ftp
      volumes:
      - name: ftps-storage
        persistentVolumeClaim:
          claimName: ftps-pv-claim